In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:
dataset=pd.read_csv("quality.csv")

In [42]:
dataset

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,StartedOnCombination,AcuteDrugGapSmall,PoorCare
0,1,0,0,18,1,731.000000,10,18,21,93,222,False,0,0
1,2,1,1,6,1,411.000000,0,8,27,19,115,False,1,0
2,3,0,0,5,3,731.000000,10,5,16,27,148,False,5,0
3,4,0,1,19,0,158.000000,34,20,14,59,242,False,0,0
4,5,8,2,19,3,449.000000,10,29,24,51,204,False,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,127,1,1,5,3,444.000000,0,7,11,11,36,False,0,0
127,128,1,0,3,2,731.000000,0,4,35,18,106,False,2,0
128,129,15,11,5,9,180.958333,95,31,56,43,265,False,3,0
129,130,0,2,14,1,216.958333,5,16,26,41,138,False,1,1
130,131,30,1,22,3,452.000000,38,53,20,103,189,False,13,0

In [43]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   MemberID              131 non-null    int64
 1   InpatientDays         131 non-null    int64
 2   ERVisits              131 non-null    int64
 3   OfficeVisits          131 non-null    int64
 4   Narcotics             131 non-null    int64
 5   DaysSinceLastERVisit  131 non-null    float64
 6   Pain                  131 non-null    int64
 7   TotalVisits           131 non-null    int64
 8   ProviderCount         131 non-null    int64
 9   MedicalClaims         131 non-null    int64
 10  ClaimLines            131 non-null    int64
 11  StartedOnCombination  131 non-null    bool
 12  AcuteDrugGapSmall     131 non-null    int64
 13  PoorCare              131 non-null    int64
dtypes: bool(1), float64(1), int64(12)
memory usage: 13.6 KB

In [44]:
#Quan=["InpatientDays", "ERVisits", "OfficeVisits", "Narcotics",  "DaysSinceLastERVisit", "Pain", "TotalVisits", "ProviderCount", "MedicalClaims", "MedicalClaims","ClaimLines", "AcuteDrugGapSmall"]

In [45]:
#Quan

In [46]:
#Qual=["MemberID","PoorCare","StartedOnCombination"]

In [47]:
#Qual

In [48]:
dataset.columns

Index(['MemberID', 'InpatientDays', 'ERVisits', 'OfficeVisits', 'Narcotics',
       'DaysSinceLastERVisit', 'Pain', 'TotalVisits', 'ProviderCount',
       'MedicalClaims', 'ClaimLines', 'StartedOnCombination',
       'AcuteDrugGapSmall', 'PoorCare'],
      dtype='str')

In [49]:
dir(dataset)

['AcuteDrugGapSmall',
 'ClaimLines',
 'DaysSinceLastERVisit',
 'ERVisits',
 'InpatientDays',
 'MedicalClaims',
 'MemberID',
 'Narcotics',
 'OfficeVisits',
 'Pain',
 'PoorCare',
 'ProviderCount',
 'StartedOnCombination',
 'T',
 'TotalVisits',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [50]:
dataset.dtypes

MemberID                  int64
InpatientDays             int64
ERVisits                  int64
OfficeVisits              int64
Narcotics                 int64
DaysSinceLastERVisit    float64
Pain                      int64
TotalVisits               int64
ProviderCount             int64
MedicalClaims             int64
ClaimLines                int64
StartedOnCombination       bool
AcuteDrugGapSmall         int64
PoorCare                  int64
dtype: object

In [51]:
dataset["StartedOnCombination"].dtype

dtype('bool')

In [52]:
dataset["InpatientDays"].dtype

dtype('int64')

In [53]:
for ColumnName in dataset.columns:
    print(ColumnName)

MemberID
InpatientDays
ERVisits
OfficeVisits
Narcotics
DaysSinceLastERVisit
Pain
TotalVisits
ProviderCount
MedicalClaims
ClaimLines
StartedOnCombination
AcuteDrugGapSmall
PoorCare

In [54]:
"""if (dataset["StartedOnCombination"].dtype==bool):
    print("qual")
else:
    print("quan")"""

'if (dataset["StartedOnCombination"].dtype==bool):\n    print("qual")\nelse:\n    print("quan")'

In [55]:
quan=[]
qual=[]
for ColumnName in dataset.columns:
    print(ColumnName)
    if (dataset[ColumnName].dtype==bool):
        qual.append(ColumnName)
    elif (dataset[ColumnName].nunique()== 2):
        qual.append(ColumnName)
    elif (dataset[ColumnName].nunique()==len(dataset)):
        qual.append(ColumnName)
    else:
        quan.append(ColumnName)

MemberID
InpatientDays
ERVisits
OfficeVisits
Narcotics
DaysSinceLastERVisit
Pain
TotalVisits
ProviderCount
MedicalClaims
ClaimLines
StartedOnCombination
AcuteDrugGapSmall
PoorCare

In [56]:
quan

['InpatientDays',
 'ERVisits',
 'OfficeVisits',
 'Narcotics',
 'DaysSinceLastERVisit',
 'Pain',
 'TotalVisits',
 'ProviderCount',
 'MedicalClaims',
 'ClaimLines',
 'AcuteDrugGapSmall']

In [57]:
qual

['MemberID', 'StartedOnCombination', 'PoorCare']

In [58]:
def QuanQual(dataset, option):
    quan = []
    qual = []

    for ColumnName in dataset.columns:
        
        if dataset[ColumnName].dtype == bool:
            qual.append(ColumnName)

        elif dataset[ColumnName].nunique() == 2:
            qual.append(ColumnName)

        elif dataset[ColumnName].nunique() == len(dataset):
            qual.append(ColumnName)

        else:
            quan.append(ColumnName)

    if option == "quan":
        return quan
    elif option == "qual":
        return qual
    else:
        return "Please choose either 'quan' or 'qual'"

In [59]:
quan=QuanQual(dataset, "quan")

In [60]:
qual=QuanQual(dataset, "qual")

In [61]:
quan

['InpatientDays',
 'ERVisits',
 'OfficeVisits',
 'Narcotics',
 'DaysSinceLastERVisit',
 'Pain',
 'TotalVisits',
 'ProviderCount',
 'MedicalClaims',
 'ClaimLines',
 'AcuteDrugGapSmall']

In [62]:
qual

['MemberID', 'StartedOnCombination', 'PoorCare']

In [63]:
dataset

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,StartedOnCombination,AcuteDrugGapSmall,PoorCare
0,1,0,0,18,1,731.000000,10,18,21,93,222,False,0,0
1,2,1,1,6,1,411.000000,0,8,27,19,115,False,1,0
2,3,0,0,5,3,731.000000,10,5,16,27,148,False,5,0
3,4,0,1,19,0,158.000000,34,20,14,59,242,False,0,0
4,5,8,2,19,3,449.000000,10,29,24,51,204,False,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,127,1,1,5,3,444.000000,0,7,11,11,36,False,0,0
127,128,1,0,3,2,731.000000,0,4,35,18,106,False,2,0
128,129,15,11,5,9,180.958333,95,31,56,43,265,False,3,0
129,130,0,2,14,1,216.958333,5,16,26,41,138,False,1,1
130,131,30,1,22,3,452.000000,38,53,20,103,189,False,13,0

# Central Tendency

In [64]:
dataset["MedicalClaims"].mean()

np.float64(43.2442748091603)

In [65]:
dataset["MedicalClaims"].median()

np.float64(37.0)

In [66]:
dataset["MedicalClaims"].mode()

0    17
1    19
Name: MedicalClaims, dtype: int64

In [73]:
dataset.describe()

,MemberID,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,AcuteDrugGapSmall,PoorCare
count,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000
mean,66.000000,2.717557,1.496183,13.229008,4.572519,480.567112,15.557252,17.442748,23.984733,43.244275,142.862595,2.694656,0.251908
std,37.960506,5.099434,2.167501,9.077076,9.713615,274.767240,20.418001,12.298318,13.670285,28.886540,91.629921,6.983379,0.435775
min,1.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,5.000000,11.000000,20.000000,0.000000,0.000000
25%,33.500000,0.000000,0.000000,7.000000,0.000000,206.958333,1.000000,8.000000,15.000000,25.500000,83.500000,0.000000,0.000000
50%,66.000000,0.000000,1.000000,12.000000,1.000000,640.958333,8.000000,15.000000,20.000000,37.000000,120.000000,1.000000,0.000000
75%,98.500000,3.000000,2.000000,18.500000,3.000000,731.000000,23.000000,22.500000,30.000000,49.500000,185.000000,3.000000,0.500000
max,131.000000,30.000000,11.000000,46.000000,59.000000,731.000000,104.000000,69.000000,82.000000,194.000000,577.000000,71.000000,1.000000

In [74]:
descriptive=pd.DataFrame()

In [75]:
descriptive=pd.DataFrame(index =["Mean", "Median", "Mode"],columns=quan)

descriptive

In [83]:
descriptive=pd.DataFrame(index =["Mean", "Median", "Mode"],columns=quan)
for ColumnName in quan:
    descriptive.loc["Mean", ColumnName] = dataset[ColumnName].mean()
    descriptive.loc["Median", ColumnName] = dataset[ColumnName].median()
    descriptive.loc["Mode", ColumnName] = dataset[ColumnName].mode()[0]

In [84]:
descriptive

,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,AcuteDrugGapSmall
Mean,2.717557,1.496183,13.229008,4.572519,480.567112,15.557252,17.442748,23.984733,43.244275,142.862595,2.694656
Median,0.0,1.0,12.0,1.0,640.958333,8.0,15.0,20.0,37.0,120.0,1.0
Mode,0,0,9,0,731.0,0,8,20,17,65,0

# Percentile

In [85]:
import numpy as np

In [86]:
np.percentile(dataset["MedicalClaims"],100)

np.float64(194.0)

In [89]:
descriptive=pd.DataFrame(index =["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "99%", "Q4:100%"],columns=quan)
for ColumnName in quan:
    descriptive.loc["Mean", ColumnName] = dataset[ColumnName].mean()
    descriptive.loc["Median", ColumnName] = dataset[ColumnName].median()
    descriptive.loc["Mode", ColumnName] = dataset[ColumnName].mode()[0]
    descriptive.loc["Q1:25%", ColumnName] = dataset.describe()[ColumnName]["25%"]
    descriptive.loc["Q2:50%", ColumnName] = dataset.describe()[ColumnName]["50%"]
    descriptive.loc["Q3:75%", ColumnName] = dataset.describe()[ColumnName]["75%"]
    descriptive.loc["99%", ColumnName] = np.percentile(dataset[ColumnName], 99)
    descriptive.loc["Q4:100%", ColumnName] = dataset.describe()[ColumnName]["max"]

In [90]:
descriptive

,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,AcuteDrugGapSmall
Mean,2.717557,1.496183,13.229008,4.572519,480.567112,15.557252,17.442748,23.984733,43.244275,142.862595,2.694656
Median,0.0,1.0,12.0,1.0,640.958333,8.0,15.0,20.0,37.0,120.0,1.0
Mode,0,0,9,0,731.0,0,8,20,17,65,0
Q1:25%,0.0,0.0,7.0,0.0,206.958333,1.0,8.0,15.0,25.5,83.5,0.0
Q2:50%,0.0,1.0,12.0,1.0,640.958333,8.0,15.0,20.0,37.0,120.0,1.0
Q3:75%,3.0,2.0,18.5,3.0,731.0,23.0,22.5,30.0,49.5,185.0,3.0
99%,26.7,8.0,45.7,44.2,731.0,94.1,63.2,74.2,155.4,514.3,16.7
Q4:100%,30.0,11.0,46.0,59.0,731.0,104.0,69.0,82.0,194.0,577.0,71.0

# IQR for Detecting Outliers

In [110]:
descriptive=pd.DataFrame(index=["Mean", "Median", "Mode", "Q1:25%", "Q2:50%", "Q3:75%", "99%", "Q4:100%","IQR", "1.5Rule", "Lesser", "Greater"],columns=quan)
for ColumnName in quan:
    descriptive.loc["Mean",ColumnName]=dataset[ColumnName].mean()
    descriptive.loc["Median", ColumnName] = dataset[ColumnName].median()
    descriptive.loc["Mode", ColumnName] = dataset[ColumnName].mode()[0]
    descriptive.loc["Q1:25%", ColumnName] = dataset.describe()[ColumnName]["25%"]
    descriptive.loc["Q2:50%", ColumnName] = dataset.describe()[ColumnName]["50%"]
    descriptive.loc["Q3:75%", ColumnName] = dataset.describe()[ColumnName]["75%"]
    descriptive.loc["99%", ColumnName] = np.percentile(dataset[ColumnName], 99)
    descriptive.loc["Q4:100%", ColumnName] = dataset.describe()[ColumnName]["max"]
    descriptive.loc["IQR", ColumnName]=descriptive.loc["Q3:75%", ColumnName]-descriptive.loc["Q1:25%", ColumnName]
    descriptive.loc["1.5Rule", ColumnName]=1.5 * descriptive.loc["IQR", ColumnName]
    descriptive.loc["Lesser", ColumnName]=descriptive.loc["Q1:25%", ColumnName]-descriptive.loc["1.5Rule", ColumnName]
    descriptive.loc["Greater", ColumnName]=descriptive.loc["Q3:75%", ColumnName]+descriptive.loc["1.5Rule", ColumnName]
    descriptive.loc["Min", ColumnName]=dataset[ColumnName].min()
    descriptive.loc["Max", ColumnName]=dataset[ColumnName].max()

In [111]:
descriptive

,InpatientDays,ERVisits,OfficeVisits,Narcotics,DaysSinceLastERVisit,Pain,TotalVisits,ProviderCount,MedicalClaims,ClaimLines,AcuteDrugGapSmall
Mean,2.717557,1.496183,13.229008,4.572519,480.567112,15.557252,17.442748,23.984733,43.244275,142.862595,2.694656
Median,0.0,1.0,12.0,1.0,640.958333,8.0,15.0,20.0,37.0,120.0,1.0
Mode,0,0,9,0,731.0,0,8,20,17,65,0
Q1:25%,0.0,0.0,7.0,0.0,206.958333,1.0,8.0,15.0,25.5,83.5,0.0
Q2:50%,0.0,1.0,12.0,1.0,640.958333,8.0,15.0,20.0,37.0,120.0,1.0
Q3:75%,3.0,2.0,18.5,3.0,731.0,23.0,22.5,30.0,49.5,185.0,3.0
99%,26.7,8.0,45.7,44.2,731.0,94.1,63.2,74.2,155.4,514.3,16.7
Q4:100%,30.0,11.0,46.0,59.0,731.0,104.0,69.0,82.0,194.0,577.0,71.0
IQR,3.0,2.0,11.5,3.0,524.041667,22.0,14.5,15.0,24.0,101.5,3.0
1.5Rule,4.5,3.0,17.25,4.5,786.0625,33.0,21.75,22.5,36.0,152.25,4.5
Lesser,-4.5,-3.0,-10.25,-4.5,-579.104167,-32.0,-13.75,-7.5,-10.5,-68.75,-4.5
Greater,7.5,5.0,35.75,7.5,1517.0625,56.0,44.25,52.5,85.5,337.25,7.5
Min,0,0,0,0,6.0,0,0,5,11,20,0
Max,30,11,46,59,731.0,104,69,82,194,577,71